### ISSUE TITLE
rename main.ml to cui.ml and apply the separation

### ISSUE THREAD

**Issue by drafear** [kuis-isle3sw/IoPLMaterials#32]
For example, Fig 4.1 in [textbook/chap04-1.pdf](https://github.com/kuis-isle3sw/IoPLMaterials/blob/master/textbook/chap04-1.pdf) shows the changes in `main.ml` but the actual needed changes is in `cui.ml` and `main.ml`.

**Comment by ksuenaga** [comment]
Is there any confusion still in the current version?

**Comment by ksuenaga** [comment]
Thank you for your contribution!
