### ISSUE TITLE
Mention about the VSCode OCaml Platform

### ISSUE THREAD

**Issue by imbsky** [kuis-isle3sw/IoPLMaterials#36]
https://github.com/ocamllabs/vscode-ocaml-platform

**Comment by ksuenaga** [comment]
I'm happy to consider merging if you can draft the text and make a pull request.

**Comment by imbsky** [comment]
Thank you. I'm a little busy this month and may be a little late, but I will work on this soon.

**Comment by imbsky** [comment]
(If someone wants to take this, feel free to take this.)
