### ISSUE TITLE
Mention about the OCaml LSP

### ISSUE THREAD

**Issue by imbsky** [kuis-isle3sw/IoPLMaterials#37]
https://github.com/ocaml/ocaml-lsp

**Comment by ksuenaga** [comment]
In which context?

**Comment by imbsky** [comment]
LSP has many advantages. See below for more information.
https://langserver.org

**Comment by imbsky** [comment]
and I think people who have experience with other languages are probably more familiar with LSP than Merlin. In that sense, I think it's a relatively good idea to mention about the LSP in the setting up guide.
