### ISSUE TITLE
dune: command not found in travis CI

### ISSUE THREAD

**Issue by sp4ghet** [kuis-isle3sw/IoPLMaterials#47]
This might not be the best place to file issues regarding the github education environment but the Travis CI build seems to be failing recently due to bash not being able to find dune in the docker environment.

Here is a link to the build, but you might need permissions to view it. (This is mainly directed to @ksuenaga since he is probably the only other person who can see the build).
https://travis-ci.com/github/kuis-isle3sw/isle3sw-2020-interpreter-sp4ghet/builds/172534948

![image](https://user-images.githubusercontent.com/8775460/85317892-1841a380-b4fa-11ea-8cbe-548ed4286afd.png)

**Comment by imbsky** [comment]
If you need some pointers, feel free to tag me :)
