### ISSUE TITLE
寄付について/About Donation

### ISSUE THREAD

**Issue by i10416** [kuis-isle3sw/IoPLMaterials#66]
このプロジェクトへの GitHub Sponsors, PayPal や 暗号通貨での寄付は受け付けていますか(or 受付予定はありますか)
Does/Will this project accept donation via GitHub Sponsors, Paypal or crypto currency?

https://github.com/kuis-isle3sw/IoPLMaterials#%E3%81%94%E5%AF%84%E4%BB%98%E3%81%AE%E3%81%8A%E9%A1%98%E3%81%84

**Comment by ksuenaga** [comment]
ありがとうございます．現在のところは GitHub Sponsors 等でのご寄付は受け付けておりません．
