### ISSUE TITLE
License

### ISSUE THREAD

**Issue by i10416** [kuis-isle3sw/IoPLMaterials#67]
Under which license is this repo published?

From the GitHub page on [Licensing a repository](https://docs.github.com/en/github/creating-cloning-and-archiving-repositories/creating-a-repository-on-github/licensing-a-repository#choosing-the-right-license):

> Without a license, the default copyright laws apply, meaning that you retain all rights to your source code and no one may reproduce, distribute, or create derivative works from your work.

**Comment by ksuenaga** [comment]
I'll add LICENSE file later.  The policy will be CC BY-NC-ND.
